run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - misspell
    - gosec
    - unconvert
    - goconst
    - goimports
    - prealloc
    - unused
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 